# データベース専用 Docker Compose
services:
  mysql:
    image: mysql:8.0
    container_name: aiapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: aiapp_dev
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - aiapp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    restart: unless-stopped

networks:
  aiapp-network:
    external: true
    name: aiapp-network

volumes:
  mysql_data:
    driver: local