name: deploy-backend-containerapps
on:
  push:
    branches: ["main"]
  workflow_dispatch:
env:
  CONTAINER_APP_NAME: ca-api-ai-learning-prod
  RESOURCE_GROUP: rg-ai-learning-prod
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/backend-api:${{ github.sha }}
      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/backend-api:${{ github.sha }}
          targetPort: 3001
